// Copyright NVIDIA Corporation 2009-2011
// TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
// *AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
// OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA OR ITS SUPPLIERS
// BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
// WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
// BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS)
// ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS
// BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES

#pragma once

#include <QGLWidget>
#include <nvutil/SmartPtr.h>

#include <nvgl/RenderTargetGL.h>
#include <nvgl/RenderContextGLFormat.h>
#include <nvui/SceneRenderer.h>
#include <SceniXWidget.h>
#include "SceniXQGLContext.h"

#include "ui/HumanInterfaceDevice.h"

/* Extract from Qt documentation.
Note that under Windows, the QGLContext belonging to a QGLWidget has to be recreated when the QGLWidget is reparented. 
This is necessary due to limitations on the Windows platform. This will most likely cause problems for users that have 
subclassed and installed their own QGLContext on a QGLWidget. It is possible to work around this issue by putting the 
QGLWidget inside a dummy widget and then reparenting the dummy widget, instead of the QGLWidget. This will side-step the
issue altogether, and is what we recommend for users that need this kind of functionality.
*/
class SceniXQGLWidget : public QWidget, public HumanInterfaceDevice
{
public:
    SceniXQGLWidget(QWidget *parent = 0, const nvgl::RenderContextGLFormat &format = nvgl::RenderContextGLFormat(), SceniXQGLWidget *shareWidget = 0);
    virtual ~SceniXQGLWidget();

    using QWidget::update;

    virtual void resizeEvent( QResizeEvent *event );

    const nvgl::SmartRenderContextGL & getRenderContext() const;
    const nvgl::SmartRenderTargetGL & getRenderTarget() const;

    bool event( QEvent *event );

    bool setFormat( const nvgl::RenderContextGLFormat &format );
    nvgl::RenderContextGLFormat getFormat() const;

    QPaintEngine *paintEngine() const;

    virtual void keyPressEvent( QKeyEvent *event );
    virtual void keyReleaseEvent( QKeyEvent *event );

    virtual void mousePressEvent( QMouseEvent *event );
    virtual void mouseReleaseEvent( QMouseEvent *event );
    virtual void mouseMoveEvent( QMouseEvent *event );
    virtual void wheelEvent( QWheelEvent *event );

    virtual unsigned int getNumberOfAxes() const;
    virtual std::string getAxisName( unsigned int axis ) const;
    virtual unsigned int getNumberOfKeys() const;
    virtual std::string getKeyName( unsigned int key ) const;

    virtual void triggerRepaint();
protected:
    /** \brief This function is being called after setting a new format. At this time the new RenderTarget and the old RenderTarget
             is available. All references to the old RenderTarget need to be released here.
      \param oldTarget The RenderTarget for the old format.
      \param newTarget The RenderTarget for the new format.
  **/
    virtual void onRenderTargetChanged( const nvgl::SmartRenderTargetGL &oldTarget, const nvgl::SmartRenderTargetGL &newTarget );

    virtual void initializeGL();
    virtual void resizeGL( int width, int height );
    virtual void paintGL();

public:
    // HID
    REFLECTION_INFO( SceniXQGLWidget )

    BEGIN_REFLECT_STATIC_PROPERTIES( SceniXQGLWidget )
    ADD_PROPERTY_RO_MEMBER( Mouse_Left, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Mouse_Middle, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Mouse_Right, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Mouse_Position, nvmath::Vec2i, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Mouse_Wheel, int, SEMANTIC_VALUE );

    // keyboard
    ADD_PROPERTY_RO_MEMBER( Key_Escape, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Tab, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Backtab, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Backspace, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Return, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Enter, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Insert, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Delete, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Pause, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Print, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_SysReq, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Clear, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Home, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_End, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Left, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Up, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Right, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Down, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_PageUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_PageDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Shift, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Control, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Meta, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Alt, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AltGr, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_CapsLock, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_NumLock, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ScrollLock, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F1, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F2, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F3, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F4, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F5, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F6, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F7, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F8, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F9, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F10, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F11, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F12, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F13, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F14, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F15, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F16, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F17, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F18, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F19, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F20, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F21, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F22, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F23, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F24, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F25, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F26, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F27, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F28, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F29, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F30, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F31, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F32, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F33, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F34, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F35, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Super_L, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Super_R, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Menu, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hyper_L, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hyper_R, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Help, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Direction_L, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Direction_R, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Space, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Any, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Exclam, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_QuoteDbl, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_NumberSign, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dollar, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Percent, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ampersand, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Apostrophe, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ParenLeft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ParenRight, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Asterisk, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Plus, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Comma, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Minus, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Period, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Slash, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_0, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_1, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_2, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_3, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_4, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_5, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_6, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_7, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_8, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_9, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Colon, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Semicolon, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Less, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Equal, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Greater, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Question, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_At, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_A, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_B, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_C, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_D, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_E, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_F, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_G, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_H, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_I, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_J, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_K, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_L, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_M, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_N, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_O, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_P, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Q, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_R, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_S, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_T, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_U, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_V, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_W, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_X, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Y, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Z, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BracketLeft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Backslash, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BracketRight, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AsciiCircum, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Underscore, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_QuoteLeft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BraceLeft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Bar, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BraceRight, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AsciiTilde, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_nobreakspace, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_exclamdown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_cent, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_sterling, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_currency, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_yen, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_brokenbar, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_section, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_diaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_copyright, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ordfeminine, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_guillemotleft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_notsign, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_hyphen, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_registered, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_macron, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_degree, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_plusminus, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_twosuperior, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_threesuperior, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_acute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_mu, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_paragraph, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_periodcentered, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_cedilla, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_onesuperior, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_masculine, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_guillemotright, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_onequarter, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_onehalf, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_threequarters, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_questiondown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Agrave, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Aacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Acircumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Atilde, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Adiaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Aring, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AE, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ccedilla, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Egrave, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Eacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ecircumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ediaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Igrave, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Iacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Icircumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Idiaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ETH, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ntilde, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ograve, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Oacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ocircumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Otilde, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Odiaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_multiply, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ooblique, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ugrave, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Uacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Ucircumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Udiaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Yacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_THORN, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ssharp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_division, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ydiaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Multi_key, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Codeinput, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_SingleCandidate, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MultipleCandidate, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_PreviousCandidate, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Mode_switch, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Kanji, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Muhenkan, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Henkan, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Romaji, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hiragana, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Katakana, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hiragana_Katakana, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Zenkaku, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hankaku, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Zenkaku_Hankaku, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Touroku, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Massyo, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Kana_Lock, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Kana_Shift, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Eisu_Shift, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Eisu_toggle, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Start, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_End, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Hanja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Jamo, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Romaja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Jeonja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Banja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_PreHanja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_PostHanja, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangul_Special, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Grave, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Acute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Circumflex, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Tilde, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Macron, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Breve, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Abovedot, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Diaeresis, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Abovering, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Doubleacute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Caron, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Cedilla, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Ogonek, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Iota, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Voiced_Sound, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Semivoiced_Sound, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Belowdot, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Hook, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Dead_Horn, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Back, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Forward, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Stop, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Refresh, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_VolumeDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_VolumeMute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_VolumeUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BassBoost, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BassUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BassDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_TrebleUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_TrebleDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaPlay, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaStop, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaPrevious, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaNext, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaRecord, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_HomePage, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Favorites, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Search, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Standby, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_OpenUrl, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchMail, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchMedia, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch0, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch1, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch2, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch3, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch4, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch5, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch6, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch7, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch8, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Launch9, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchA, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchC, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchD, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchE, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LaunchF, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MonBrightnessUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MonBrightnessDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_KeyboardLightOnOff, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_KeyboardBrightnessUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_KeyboardBrightnessDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_PowerOff, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_WakeUp, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Eject, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ScreenSaver, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_WWW, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Memo, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LightBulb, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Shop, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_History, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AddFavorite, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_HotLinks, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BrightnessAdjust, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Finance, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Community, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AudioRewind, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_BackForward, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ApplicationLeft, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ApplicationRight, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Book, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_CD, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Calculator, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ToDoList, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ClearGrab, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Close, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Copy, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Cut, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Display, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_DOS, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Documents, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Excel, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Explorer, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Game, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Go, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_iTouch, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_LogOff, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Market, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Meeting, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MenuKB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MenuPB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MySites, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_News, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_OfficeHome, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Option, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Paste, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Phone, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Calendar, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Reply, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Reload, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_RotateWindows, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_RotationPB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_RotationKB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Save, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Send, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Spell, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_SplitScreen, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Support, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_TaskPane, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Terminal, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Tools, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Travel, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Video, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Word, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Xfer, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ZoomIn, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ZoomOut, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Away, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Messenger, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_WebCam, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MailForward, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Pictures, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Music, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Battery, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Bluetooth, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_WLAN, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_UWB, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AudioForward, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AudioRepeat, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AudioRandomPlay, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Subtitle, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_AudioCycleTrack, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Time, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hibernate, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_View, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_TopMenu, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_PowerDown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Suspend, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_ContrastAdjust, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_MediaLast, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_unknown, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Call, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Context1, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Context2, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Context3, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Context4, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Flip, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Hangup, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_No, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Select, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Yes, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Execute, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Printer, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Play, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Sleep, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Zoom, bool, SEMANTIC_VALUE );
    ADD_PROPERTY_RO_MEMBER( Key_Cancel, bool, SEMANTIC_VALUE );
    END_REFLECT_STATIC_PROPERTIES()

    protected:
        class SceniXQGLWidgetPrivate : public QGLWidget
    {
        public:
        SceniXQGLWidgetPrivate( SceniXQGLWidget *parent, const nvgl::RenderContextGLFormat &glFormat, QGLWidget *shareWidget );
        virtual ~SceniXQGLWidgetPrivate();

        const nvgl::SmartRenderContextGL & getRenderContext() const;
        const nvgl::SmartRenderTargetGL  & getRenderTarget() const;
        protected:
        virtual void initializeGL();
        virtual void resizeGL( int width, int height );
        virtual void paintGL();

        nvgl::SmartRenderTargetGL  m_renderTargetGL;
    };

    SceniXQGLWidgetPrivate *m_glWidget;

    /** Called on hid (keyboard, mouse) events. Call always the base class in your own event handler! **/
    virtual void hidNotify( nvutil::PropertyId propertyId );
private:
    // HID
    struct KeyInfo {
        KeyInfo() : propertyId(0), member(0), name(0) {}
        KeyInfo( nvutil::PropertyId id, bool SceniXQGLWidget::*keyMember, const char *keyName ) : propertyId(id), member( keyMember ), name(keyName) {}

        nvutil::PropertyId     propertyId;
        bool SceniXQGLWidget::*member;
        const char            *name;
    };

    nvutil::PropertyId getQtMouseButtonProperty( Qt::MouseButton button ) const;

    typedef std::vector<KeyInfo> KeyInfoVector;
    typedef std::map<Qt::Key, KeyInfo> KeyInfoMap;

    KeyInfoMap m_keyProperties;  //!< Map Qt key to propertyId
    KeyInfoVector m_keyInfos;  //!< For indexed access

    // mouse members
    bool m_propMouse_Left;
    bool m_propMouse_Middle;
    bool m_propMouse_Right;
    nvmath::Vec2i m_propMouse_Position;
    int m_propMouse_Wheel;

    nvutil::PropertyId PID_Mouse_Left;
    nvutil::PropertyId PID_Mouse_Middle;
    nvutil::PropertyId PID_Mouse_Right;
    nvutil::PropertyId PID_Mouse_Position;
    nvutil::PropertyId PID_Mouse_Wheel;

    // keyboard members
    bool m_propKey_Escape;
    bool m_propKey_Tab;
    bool m_propKey_Backtab;
    bool m_propKey_Backspace;
    bool m_propKey_Return;
    bool m_propKey_Enter;
    bool m_propKey_Insert;
    bool m_propKey_Delete;
    bool m_propKey_Pause;
    bool m_propKey_Print;
    bool m_propKey_SysReq;
    bool m_propKey_Clear;
    bool m_propKey_Home;
    bool m_propKey_End;
    bool m_propKey_Left;
    bool m_propKey_Up;
    bool m_propKey_Right;
    bool m_propKey_Down;
    bool m_propKey_PageUp;
    bool m_propKey_PageDown;
    bool m_propKey_Shift;
    bool m_propKey_Control;
    bool m_propKey_Meta;
    bool m_propKey_Alt;
    bool m_propKey_AltGr;
    bool m_propKey_CapsLock;
    bool m_propKey_NumLock;
    bool m_propKey_ScrollLock;
    bool m_propKey_F1;
    bool m_propKey_F2;
    bool m_propKey_F3;
    bool m_propKey_F4;
    bool m_propKey_F5;
    bool m_propKey_F6;
    bool m_propKey_F7;
    bool m_propKey_F8;
    bool m_propKey_F9;
    bool m_propKey_F10;
    bool m_propKey_F11;
    bool m_propKey_F12;
    bool m_propKey_F13;
    bool m_propKey_F14;
    bool m_propKey_F15;
    bool m_propKey_F16;
    bool m_propKey_F17;
    bool m_propKey_F18;
    bool m_propKey_F19;
    bool m_propKey_F20;
    bool m_propKey_F21;
    bool m_propKey_F22;
    bool m_propKey_F23;
    bool m_propKey_F24;
    bool m_propKey_F25;
    bool m_propKey_F26;
    bool m_propKey_F27;
    bool m_propKey_F28;
    bool m_propKey_F29;
    bool m_propKey_F30;
    bool m_propKey_F31;
    bool m_propKey_F32;
    bool m_propKey_F33;
    bool m_propKey_F34;
    bool m_propKey_F35;
    bool m_propKey_Super_L;
    bool m_propKey_Super_R;
    bool m_propKey_Menu;
    bool m_propKey_Hyper_L;
    bool m_propKey_Hyper_R;
    bool m_propKey_Help;
    bool m_propKey_Direction_L;
    bool m_propKey_Direction_R;
    bool m_propKey_Space;
    bool m_propKey_Any;
    bool m_propKey_Exclam;
    bool m_propKey_QuoteDbl;
    bool m_propKey_NumberSign;
    bool m_propKey_Dollar;
    bool m_propKey_Percent;
    bool m_propKey_Ampersand;
    bool m_propKey_Apostrophe;
    bool m_propKey_ParenLeft;
    bool m_propKey_ParenRight;
    bool m_propKey_Asterisk;
    bool m_propKey_Plus;
    bool m_propKey_Comma;
    bool m_propKey_Minus;
    bool m_propKey_Period;
    bool m_propKey_Slash;
    bool m_propKey_0;
    bool m_propKey_1;
    bool m_propKey_2;
    bool m_propKey_3;
    bool m_propKey_4;
    bool m_propKey_5;
    bool m_propKey_6;
    bool m_propKey_7;
    bool m_propKey_8;
    bool m_propKey_9;
    bool m_propKey_Colon;
    bool m_propKey_Semicolon;
    bool m_propKey_Less;
    bool m_propKey_Equal;
    bool m_propKey_Greater;
    bool m_propKey_Question;
    bool m_propKey_At;
    bool m_propKey_A;
    bool m_propKey_B;
    bool m_propKey_C;
    bool m_propKey_D;
    bool m_propKey_E;
    bool m_propKey_F;
    bool m_propKey_G;
    bool m_propKey_H;
    bool m_propKey_I;
    bool m_propKey_J;
    bool m_propKey_K;
    bool m_propKey_L;
    bool m_propKey_M;
    bool m_propKey_N;
    bool m_propKey_O;
    bool m_propKey_P;
    bool m_propKey_Q;
    bool m_propKey_R;
    bool m_propKey_S;
    bool m_propKey_T;
    bool m_propKey_U;
    bool m_propKey_V;
    bool m_propKey_W;
    bool m_propKey_X;
    bool m_propKey_Y;
    bool m_propKey_Z;
    bool m_propKey_BracketLeft;
    bool m_propKey_Backslash;
    bool m_propKey_BracketRight;
    bool m_propKey_AsciiCircum;
    bool m_propKey_Underscore;
    bool m_propKey_QuoteLeft;
    bool m_propKey_BraceLeft;
    bool m_propKey_Bar;
    bool m_propKey_BraceRight;
    bool m_propKey_AsciiTilde;
    bool m_propKey_nobreakspace;
    bool m_propKey_exclamdown;
    bool m_propKey_cent;
    bool m_propKey_sterling;
    bool m_propKey_currency;
    bool m_propKey_yen;
    bool m_propKey_brokenbar;
    bool m_propKey_section;
    bool m_propKey_diaeresis;
    bool m_propKey_copyright;
    bool m_propKey_ordfeminine;
    bool m_propKey_guillemotleft;
    bool m_propKey_notsign;
    bool m_propKey_hyphen;
    bool m_propKey_registered;
    bool m_propKey_macron;
    bool m_propKey_degree;
    bool m_propKey_plusminus;
    bool m_propKey_twosuperior;
    bool m_propKey_threesuperior;
    bool m_propKey_acute;
    bool m_propKey_mu;
    bool m_propKey_paragraph;
    bool m_propKey_periodcentered;
    bool m_propKey_cedilla;
    bool m_propKey_onesuperior;
    bool m_propKey_masculine;
    bool m_propKey_guillemotright;
    bool m_propKey_onequarter;
    bool m_propKey_onehalf;
    bool m_propKey_threequarters;
    bool m_propKey_questiondown;
    bool m_propKey_Agrave;
    bool m_propKey_Aacute;
    bool m_propKey_Acircumflex;
    bool m_propKey_Atilde;
    bool m_propKey_Adiaeresis;
    bool m_propKey_Aring;
    bool m_propKey_AE;
    bool m_propKey_Ccedilla;
    bool m_propKey_Egrave;
    bool m_propKey_Eacute;
    bool m_propKey_Ecircumflex;
    bool m_propKey_Ediaeresis;
    bool m_propKey_Igrave;
    bool m_propKey_Iacute;
    bool m_propKey_Icircumflex;
    bool m_propKey_Idiaeresis;
    bool m_propKey_ETH;
    bool m_propKey_Ntilde;
    bool m_propKey_Ograve;
    bool m_propKey_Oacute;
    bool m_propKey_Ocircumflex;
    bool m_propKey_Otilde;
    bool m_propKey_Odiaeresis;
    bool m_propKey_multiply;
    bool m_propKey_Ooblique;
    bool m_propKey_Ugrave;
    bool m_propKey_Uacute;
    bool m_propKey_Ucircumflex;
    bool m_propKey_Udiaeresis;
    bool m_propKey_Yacute;
    bool m_propKey_THORN;
    bool m_propKey_ssharp;
    bool m_propKey_division;
    bool m_propKey_ydiaeresis;
    bool m_propKey_Multi_key;
    bool m_propKey_Codeinput;
    bool m_propKey_SingleCandidate;
    bool m_propKey_MultipleCandidate;
    bool m_propKey_PreviousCandidate;
    bool m_propKey_Mode_switch;
    bool m_propKey_Kanji;
    bool m_propKey_Muhenkan;
    bool m_propKey_Henkan;
    bool m_propKey_Romaji;
    bool m_propKey_Hiragana;
    bool m_propKey_Katakana;
    bool m_propKey_Hiragana_Katakana;
    bool m_propKey_Zenkaku;
    bool m_propKey_Hankaku;
    bool m_propKey_Zenkaku_Hankaku;
    bool m_propKey_Touroku;
    bool m_propKey_Massyo;
    bool m_propKey_Kana_Lock;
    bool m_propKey_Kana_Shift;
    bool m_propKey_Eisu_Shift;
    bool m_propKey_Eisu_toggle;
    bool m_propKey_Hangul;
    bool m_propKey_Hangul_Start;
    bool m_propKey_Hangul_End;
    bool m_propKey_Hangul_Hanja;
    bool m_propKey_Hangul_Jamo;
    bool m_propKey_Hangul_Romaja;
    bool m_propKey_Hangul_Jeonja;
    bool m_propKey_Hangul_Banja;
    bool m_propKey_Hangul_PreHanja;
    bool m_propKey_Hangul_PostHanja;
    bool m_propKey_Hangul_Special;
    bool m_propKey_Dead_Grave;
    bool m_propKey_Dead_Acute;
    bool m_propKey_Dead_Circumflex;
    bool m_propKey_Dead_Tilde;
    bool m_propKey_Dead_Macron;
    bool m_propKey_Dead_Breve;
    bool m_propKey_Dead_Abovedot;
    bool m_propKey_Dead_Diaeresis;
    bool m_propKey_Dead_Abovering;
    bool m_propKey_Dead_Doubleacute;
    bool m_propKey_Dead_Caron;
    bool m_propKey_Dead_Cedilla;
    bool m_propKey_Dead_Ogonek;
    bool m_propKey_Dead_Iota;
    bool m_propKey_Dead_Voiced_Sound;
    bool m_propKey_Dead_Semivoiced_Sound;
    bool m_propKey_Dead_Belowdot;
    bool m_propKey_Dead_Hook;
    bool m_propKey_Dead_Horn;
    bool m_propKey_Back;
    bool m_propKey_Forward;
    bool m_propKey_Stop;
    bool m_propKey_Refresh;
    bool m_propKey_VolumeDown;
    bool m_propKey_VolumeMute;
    bool m_propKey_VolumeUp;
    bool m_propKey_BassBoost;
    bool m_propKey_BassUp;
    bool m_propKey_BassDown;
    bool m_propKey_TrebleUp;
    bool m_propKey_TrebleDown;
    bool m_propKey_MediaPlay;
    bool m_propKey_MediaStop;
    bool m_propKey_MediaPrevious;
    bool m_propKey_MediaNext;
    bool m_propKey_MediaRecord;
    bool m_propKey_HomePage;
    bool m_propKey_Favorites;
    bool m_propKey_Search;
    bool m_propKey_Standby;
    bool m_propKey_OpenUrl;
    bool m_propKey_LaunchMail;
    bool m_propKey_LaunchMedia;
    bool m_propKey_Launch0;
    bool m_propKey_Launch1;
    bool m_propKey_Launch2;
    bool m_propKey_Launch3;
    bool m_propKey_Launch4;
    bool m_propKey_Launch5;
    bool m_propKey_Launch6;
    bool m_propKey_Launch7;
    bool m_propKey_Launch8;
    bool m_propKey_Launch9;
    bool m_propKey_LaunchA;
    bool m_propKey_LaunchB;
    bool m_propKey_LaunchC;
    bool m_propKey_LaunchD;
    bool m_propKey_LaunchE;
    bool m_propKey_LaunchF;
    bool m_propKey_MonBrightnessUp;
    bool m_propKey_MonBrightnessDown;
    bool m_propKey_KeyboardLightOnOff;
    bool m_propKey_KeyboardBrightnessUp;
    bool m_propKey_KeyboardBrightnessDown;
    bool m_propKey_PowerOff;
    bool m_propKey_WakeUp;
    bool m_propKey_Eject;
    bool m_propKey_ScreenSaver;
    bool m_propKey_WWW;
    bool m_propKey_Memo;
    bool m_propKey_LightBulb;
    bool m_propKey_Shop;
    bool m_propKey_History;
    bool m_propKey_AddFavorite;
    bool m_propKey_HotLinks;
    bool m_propKey_BrightnessAdjust;
    bool m_propKey_Finance;
    bool m_propKey_Community;
    bool m_propKey_AudioRewind;
    bool m_propKey_BackForward;
    bool m_propKey_ApplicationLeft;
    bool m_propKey_ApplicationRight;
    bool m_propKey_Book;
    bool m_propKey_CD;
    bool m_propKey_Calculator;
    bool m_propKey_ToDoList;
    bool m_propKey_ClearGrab;
    bool m_propKey_Close;
    bool m_propKey_Copy;
    bool m_propKey_Cut;
    bool m_propKey_Display;
    bool m_propKey_DOS;
    bool m_propKey_Documents;
    bool m_propKey_Excel;
    bool m_propKey_Explorer;
    bool m_propKey_Game;
    bool m_propKey_Go;
    bool m_propKey_iTouch;
    bool m_propKey_LogOff;
    bool m_propKey_Market;
    bool m_propKey_Meeting;
    bool m_propKey_MenuKB;
    bool m_propKey_MenuPB;
    bool m_propKey_MySites;
    bool m_propKey_News;
    bool m_propKey_OfficeHome;
    bool m_propKey_Option;
    bool m_propKey_Paste;
    bool m_propKey_Phone;
    bool m_propKey_Calendar;
    bool m_propKey_Reply;
    bool m_propKey_Reload;
    bool m_propKey_RotateWindows;
    bool m_propKey_RotationPB;
    bool m_propKey_RotationKB;
    bool m_propKey_Save;
    bool m_propKey_Send;
    bool m_propKey_Spell;
    bool m_propKey_SplitScreen;
    bool m_propKey_Support;
    bool m_propKey_TaskPane;
    bool m_propKey_Terminal;
    bool m_propKey_Tools;
    bool m_propKey_Travel;
    bool m_propKey_Video;
    bool m_propKey_Word;
    bool m_propKey_Xfer;
    bool m_propKey_ZoomIn;
    bool m_propKey_ZoomOut;
    bool m_propKey_Away;
    bool m_propKey_Messenger;
    bool m_propKey_WebCam;
    bool m_propKey_MailForward;
    bool m_propKey_Pictures;
    bool m_propKey_Music;
    bool m_propKey_Battery;
    bool m_propKey_Bluetooth;
    bool m_propKey_WLAN;
    bool m_propKey_UWB;
    bool m_propKey_AudioForward;
    bool m_propKey_AudioRepeat;
    bool m_propKey_AudioRandomPlay;
    bool m_propKey_Subtitle;
    bool m_propKey_AudioCycleTrack;
    bool m_propKey_Time;
    bool m_propKey_Hibernate;
    bool m_propKey_View;
    bool m_propKey_TopMenu;
    bool m_propKey_PowerDown;
    bool m_propKey_Suspend;
    bool m_propKey_ContrastAdjust;
    bool m_propKey_MediaLast;
    bool m_propKey_unknown;
    bool m_propKey_Call;
    bool m_propKey_Context1;
    bool m_propKey_Context2;
    bool m_propKey_Context3;
    bool m_propKey_Context4;
    bool m_propKey_Flip;
    bool m_propKey_Hangup;
    bool m_propKey_No;
    bool m_propKey_Select;
    bool m_propKey_Yes;
    bool m_propKey_Execute;
    bool m_propKey_Printer;
    bool m_propKey_Play;
    bool m_propKey_Sleep;
    bool m_propKey_Zoom;
    bool m_propKey_Cancel;
};
